=== duets/game/database/schema/root.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "root.json",
  "title": "Database",
  "description": "Root of the database",
  "type": "object",
  "required": ["countries", "genres", "instruments", "skills", "objects"],
  "properties": {
    "countries": { "$ref": "file.json#definitions/file" },
    "genres": { "$ref": "file.json#definitions/file" },
    "instruments": { "$ref": "file.json#definitions/file" },
    "skills": { "$ref": "file.json#definitions/file" },
    "objects": { "$ref": "file.json#definitions/file" }
  }
}

=== duets/game/database/def/database.json
{
  "$schema": "../schema/root.json",
  "countries": ["file:countries/cz/cz.json"],
  "genres": [
    {
      "id": "not_blvck",
      "name": "Blackgaze",
      "compatibleWith": []
    }
  ],
  "instruments": [
    {
      "id": "guitar",
      "name": "Guitar",
      "allowsAnotherInstrument": true,
      "associatedSkill": "ref:skills_guitar"
    }
  ],
  "skills": [
    {
      "id": "guitar",
      "name": "Guitar",
      "category": "Music"
    }
  ],
  "objects": [
    {
      "id": "test1",
      "name": "guitar",
      "description": "A simple guitar for testing",
      "type": {
        "Instrument": "ref:instruments_guitar"
      }
    },
    {
      "id": "test2",
      "name": "fake guitar",
      "description": "A fake guitar to test spaces in names",
      "type": {
        "Instrument": "ref:instruments_guitar"
      }
    }
  ]
}

=== duets/game/database/database.json
{
  "$schema": "./schema/root.json",
  "countries": [
    {
      "id": "CZK",
      "name": "Czech Republic",
      "population": 10690000,
      "cities": [
        {
          "id": "PRG",
          "name": "Prague",
          "population": 1309000,
          "places": [
            {
              "id": "test_1",
              "name": "Test Place",
              "rooms": [
                {
                  "id": "test_1",
                  "name": "bathroom",
                  "description": "A dark room just to test",
                  "objects": ["$objects_test1", "$objects_test2"]
                }
              ]
            },
            {
              "id": "test_2",
              "name": "Test Place 2",
              "rooms": [
                {
                  "id": "test_1",
                  "name": "kitchen",
                  "description": "A dark room just to test, but again",
                  "objects": []
                }
              ]
            },
            {
              "id": "test_3",
              "name": "Test Place 3",
              "rooms": [
                {
                  "id": "test_1",
                  "name": "kitchen",
                  "description": "A dark room just to test, but again",
                  "objects": []
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  "genres": [
    {
      "id": "not_blvck",
      "name": "Blackgaze",
      "compatibleWith": []
    }
  ],
  "instruments": [
    {
      "id": "guitar",
      "name": "Guitar",
      "allowsAnotherInstrument": true,
      "associatedSkill": "$skills_guitar"
    }
  ],
  "skills": [
    {
      "id": "guitar",
      "name": "Guitar",
      "category": "Music"
    }
  ],
  "objects": [
    {
      "id": "test1",
      "name": "guitar",
      "description": "A simple guitar for testing",
      "type": {
        "Instrument": "$instruments_guitar"
      }
    },
    {
      "id": "test2",
      "name": "fake guitar",
      "description": "A fake guitar to test spaces in names",
      "type": {
        "Instrument": "$instruments_guitar"
      }
    }
  ]
}

=== duets/game/database/generated/database.json
{"$schema":"../schema/root.json","countries":[{"$schema":"../../../schema/country.json","id":"cz","name":"Czech Republic","population":10690000,"cities":[{"$schema":"../../../../schema/city.json","id":"prg","name":"Prague","population":1309000,"places":[{"id":"test_1","name":"Test Place","rooms":[{"id":"test_1","name":"bathroom","description":"A dark room just to test","objects":[{"id":"test1","name":"guitar","description":"A simple guitar for testing","type":{"Instrument":{"id":"guitar","name":"Guitar","allowsAnotherInstrument":true,"associatedSkill":{"id":"guitar","name":"Guitar","category":"Music"}}}},{"id":"test2","name":"fake guitar","description":"A fake guitar to test spaces in names","type":{"Instrument":{"id":"guitar","name":"Guitar","allowsAnotherInstrument":true,"associatedSkill":{"id":"guitar","name":"Guitar","category":"Music"}}}}]}]}]}]}],"genres":[{"$schema":"../../schema/genre.json","id":"ambient","name":"Ambient","compatibleWith":["blackgaze","electronic"]},{"$schema":"../../schema/genre.json","id":"black-metal","name":"Black Metal","compatibleWith":["blackgaze"]},{"$schema":"../../schema/genre.json","id":"blackgaze","name":"Blackgaze","compatibleWith":["ambient","shoegaze"]},{"$schema":"../../schema/genre.json","id":"electronic","name":"Electronic","compatibleWith":["pop"]},{"$schema":"../../schema/genre.json","id":"folk","name":"Folk","compatibleWith":["pop"]},{"$schema":"../../schema/genre.json","id":"hip-hop","name":"Hip Hop","compatibleWith":[]},{"$schema":"../../schema/genre.json","id":"jazz","name":"Jazz","compatibleWith":[]},{"$schema":"../../schema/genre.json","id":"pop","name":"Pop","compatibleWith":["electronic"]},{"$schema":"../../schema/genre.json","id":"rock","name":"Rock","compatibleWith":[""]},{"$schema":"../../schema/genre.json","id":"shoegaze","name":"Shoegaze","compatibleWith":["blackgaze"]}],"instruments":[{"id":"guitar","name":"Guitar","allowsAnotherInstrument":true,"associatedSkill":{"id":"guitar","name":"Guitar","category":"Music"}}],"skills":[{"id":"guitar","name":"Guitar","category":"Music"}],"objects":[{"id":"test1","name":"guitar","description":"A simple guitar for testing","type":{"Instrument":{"id":"guitar","name":"Guitar","allowsAnotherInstrument":true,"associatedSkill":{"id":"guitar","name":"Guitar","category":"Music"}}}},{"id":"test2","name":"fake guitar","description":"A fake guitar to test spaces in names","type":{"Instrument":{"id":"guitar","name":"Guitar","allowsAnotherInstrument":true,"associatedSkill":{"id":"guitar","name":"Guitar","category":"Music"}}}}]}
